In [3]:
import numpy as np

np.random.seed(0)
Input = np.random.rand(3, 3)
x = np.random.rand(3, 3)
residual_output = Input + x

print("Input:")
print(Input)
print("\nx:")
print(x)
print("\nResidual Output (Input + x):")
print(residual_output)

Input:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]

x:
[[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]]

Residual Output (Input + x):
[[0.93225502 1.5069144  1.1316583 ]
 [1.11292774 1.34925144 0.71693017]
 [0.52471651 0.9119914  1.79628261]]


In [2]:
0.5488135+0.38344152

0.9322550199999999